In [3]:
import pandas as pd
import glob
import os
import sys

In [113]:
input_path = sys.argv[1]
output_file = sys.argv[2]

all_files = glob.glob(os.path.join(input_path,'C:/Users/Administrator/subway15-19/CARD_SUBWAY_MONTH_2016*.csv'))

all_data_frames = []

for file in all_files: 
    data_frame = pd.read_csv(file, index_col=None, encoding='utf-8') 
    all_data_frames.append(data_frame)

data_frame_concat = pd.concat(all_data_frames, axis=0, ignore_index=True) 
data_frame_concat.to_csv("2016_subway_merge.csv", index = False)

In [114]:
data_frame_concat

            사용일자       노선명   역ID       역명  승차총승객수  하차총승객수      등록일자
0       20160101       2호선   210       뚝섬    5374    5117  20160109
1       20160101       2호선   211       성수    6730    6858  20160109
2       20160101       2호선   212     건대입구   31453   33343  20160109
3       20160101       2호선   213       구의   10553    9629  20160109
4       20160101       2호선   214       강변   32259   35307  20160109
5       20160101       2호선   215     잠실나루    6116    5839  20160109
6       20160101       2호선   216       잠실   50864   45006  20160109
7       20160101       2호선   217       신천   12433   12627  20160109
8       20160101       2호선   218    종합운동장    6469    6142  20160109
9       20160101       2호선   219       삼성   19324   19310  20160109
10      20160101       2호선   220       선릉   11593    9255  20160109
11      20160101       2호선   221       역삼    9643    9718  20160109
12      20160101       2호선   222       강남   37893   39308  20160109
13      20160101       2호선   223       교대    9581    9762  20160109
14      20160101       2호선   224       서초    4359    4197  20160109
15      20160101       2호선   225       방배    5843    5921  20160109
16      20160101       2호선   226       사당   19757   21167  20160109
17      20160101       2호선   227      낙성대   14361   12727  20160109
18      20160101       2호선   228    서울대입구   25538   24441  20160109
19      20160101       2호선   229       봉천   11027   10296  20160109
20      20160101       2호선   230       신림   41158   40203  20160109
21      20160101       2호선   231      신대방   15163   14507  20160109
22      20160101       2호선   232  구로디지털단지   27016   26251  20160109
23      20160101       2호선   233       대림   18707   20509  20160109
24      20160101       2호선   234      신도림   31526   31498  20160109
25      20160101       2호선   235       문래    5927    5917  20160109
26      20160101       2호선   236    영등포구청    6489    6362  20160109
27      20160101       2호선   237       당산    8424    8935  20160109
28      20160101       2호선   238       합정   16668   16576  20160109
29      20160101       2호선   239     홍대입구   63294   63961  20160109
...          ...       ...   ...      ...     ...     ...       ...
203405  20161231       중앙선  1213       신원     185     146  20170108
203406  20161231       중앙선  1214       국수     650     739  20170108
203407  20161231       중앙선  1215       아신     569     651  20170108
203408  20161231       중앙선  1216       오빈     308     322  20170108
203409  20161231       중앙선  1217       양평    3167    3546  20170108
203410  20161231       중앙선  1218       원덕     383     417  20170108
203411  20161231       중앙선  1219       용문    2409    2838  20170108
203412  20161231  공항철도 1호선  4217       영종    1673    1571  20170108
203413  20161231       과천선  1450      선바위    6073    4690  20170108
203414  20161231       과천선  1451     경마공원   15774   16125  20170108
203415  20161231       과천선  1452      대공원    4499    4803  20170108
203416  20161231       과천선  1453       과천    4089    3213  20170108
203417  20161231       과천선  1454   정부과천청사    7465    8022  20170108
203418  20161231       과천선  1455      인덕원   18792   17171  20170108
203419  20161231       과천선  1456       평촌    9486    9105  20170108
203420  20161231       과천선  1457       범계   24935   23992  20170108
203421  20161231       분당선  1023       선릉    3495    6500  20170108
203422  20161231       분당선  1024       한티   12707   11867  20170108
203423  20161231       분당선  1025       도곡    4186    4152  20170108
203424  20161231       분당선  1026       구룡    1350    1160  20170108
203425  20161231       분당선  1027      개포동    2413    2490  20170108
203426  20161231       분당선  1028    대모산입구    2275    1956  20170108
203427  20161231       분당선  1030       수서    8035    9083  20170108
203428  20161231       분당선  1846       수원    8424    5323  20170108
203429  20161231       분당선  1847      서울숲    3987    3680  20170108
203430  20161231       분당선  1848   압구정로데오   12741   14740  20170108
203431  20161231       분당선  1849     강남구청    4485    5233  20170108
203432  20161231       분당선  1850      선정릉    3362    3531  20170108
203433  20161231       분당선  1851      가천대    4297    4404  20170108
203434  20161231       분당선  1852       태평   12893   12031  20170108

[203435 rows x 7 columns]

In [110]:
data=pd.read_csv("CARD_SUBWAY_MONTH_201809.csv", index_col=None, encoding='utf-8')
data.head()

       사용일자  노선명   역ID          역명  승차총승객수  하차총승객수      등록일자
0  20180901  7호선  2748     가산디지털단지   18115   16802  20180904
1  20180901  7호선  2749          철산   20947   21211  20180904
2  20180901  7호선  2750       광명사거리   23407   23104  20180904
3  20180901  7호선  2751          천왕    7169    6478  20180904
4  20180901  7호선  2752  온수(성공회대입구)    7067    7090  20180904

In [124]:
data2=pd.read_csv("subway_merge_5.csv", index_col=None, encoding='utf-8')
data2

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

In [134]:
import calendar
weekday=calendar.weekday(2019,5,13)
print(weekday)

0

In [133]:
import datetime
datetime.date(2019,5,19).isocalendar()[1]

20