In [2]:
import pandas as pd
import glob
import os
import sys

In [10]:
data2=pd.read_csv("subway_merge.csv", index_col=None, encoding='utf-8')
data2.head()
type(data2)
import datetime
# datetime.date(2016,1,1).isocalendar()[1:]
date=data2.iloc[:1000,0]
# type(date)
date5=data2.iloc[:1000,:]
date5.head()
# date.head()
data3=list(date)
#data3
#int('01')

In [11]:
datelist=[]
for i in range(len(data3)):
    date2=str(data3[i])
    year=date2[:4]
    month=date2[4:6]
    day=date2[6:8]
    da=datetime.date(int(year),int(month),int(day)).isocalendar()[1:]
    datelist.append(da)
datelist
date5["A"] = datelist
date5

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

         사용일자       노선명   역ID          역명   승차총승객수  하차총승객수        등록일자       A
0    20150101       2호선   236       영등포구청   6199.0    6219  20151217.0  (1, 4)
1    20150101       2호선   237          당산   7982.0    8946  20151217.0  (1, 4)
2    20150101       2호선   238          합정  17406.0   15241  20151217.0  (1, 4)
3    20150101       2호선   239        홍대입구  57469.0   51756  20151217.0  (1, 4)
4    20150101       2호선   240          신촌  30115.0   27766  20151217.0  (1, 4)
5    20150101       2호선   241          이대  11553.0   12272  20151217.0  (1, 4)
6    20150101       2호선   242          아현   3510.0    3578  20151217.0  (1, 4)
7    20150101       2호선   243         충정로   3865.0    3942  20151217.0  (1, 4)
8    20150101       2호선   244          용답   1350.0    1356  20151217.0  (1, 4)
9    20150101       2호선   245          신답    518.0     565  20151217.0  (1, 4)
10   20150101       2호선   246         신설동   1669.0    1381  20151217.0  (1, 4)
11   20150101       2호선   247         도림천    303.0     336  20151217.0  (1, 4)
12   20150101       2호선   248        양천구청   2726.0    3024  20151217.0  (1, 4)
13   20150101       2호선   249       신정네거리   5210.0    5531  20151217.0  (1, 4)
14   20150101       2호선   250          용두    975.0    1074  20151217.0  (1, 4)
15   20150101       3호선   309          지축    515.0     538  20151217.0  (1, 4)
16   20150101       3호선   310         구파발   6879.0    6260  20151217.0  (1, 4)
17   20150101       3호선   311         연신내  20031.0   19470  20151217.0  (1, 4)
18   20150101       3호선   312          불광   9519.0   11029  20151217.0  (1, 4)
19   20150101  공항철도 1호선  4204    디지털미디어시티   2747.0    2532  20151217.0  (1, 4)
20   20150101  공항철도 1호선  4207        김포공항   6067.0    4112  20151217.0  (1, 4)
21   20150101  공항철도 1호선  4208          계양   4590.0    4596  20151217.0  (1, 4)
22   20150101  공항철도 1호선  4209          검암   8151.0    8327  20151217.0  (1, 4)
23   20150101  공항철도 1호선  4210      청라국제도시   1838.0    1927  20151217.0  (1, 4)
24   20150101  공항철도 1호선  4211          운서   3691.0    3823  20151217.0  (1, 4)
25   20150101  공항철도 1호선  4212      공항화물청사   1120.0    1122  20151217.0  (1, 4)
26   20150101  공항철도 1호선  4213      인천국제공항  13610.0   12996  20151217.0  (1, 4)
27   20150101       4호선   425          회현   7465.0    7574  20151217.0  (1, 4)
28   20150101       4호선   426         서울역   3943.0   10823  20151217.0  (1, 4)
29   20150101       4호선   427        숙대입구   6380.0    6033  20151217.0  (1, 4)
..        ...       ...   ...         ...      ...     ...         ...     ...
970  20150102       6호선  2644         돌곶이   9309.0    8308  20151217.0  (1, 5)
971  20150102       6호선  2645          석계  13506.0   13201  20151217.0  (1, 5)
972  20150102       6호선  2646        태릉입구   4972.0    5333  20151217.0  (1, 5)
973  20150102       6호선  2647         화랑대  12017.0    9109  20151217.0  (1, 5)
974  20150102       6호선  2648  봉화산(서울의료원)   9832.0    9100  20151217.0  (1, 5)
975  20150102       7호선  2711          장암   2175.0     687  20151217.0  (1, 5)
976  20150102       7호선  2712         도봉산  10826.0    9761  20151217.0  (1, 5)
977  20150102       7호선  2713         수락산  14201.0   13409  20151217.0  (1, 5)
978  20150102       7호선  2714          마들  12706.0   11406  20151217.0  (1, 5)
979  20150102       7호선  2715          노원  25374.0   27079  20151217.0  (1, 5)
980  20150102       7호선  2716          중계  15409.0   13671  20151217.0  (1, 5)
981  20150102       7호선  2717          하계  20420.0   19154  20151217.0  (1, 5)
982  20150102       7호선  2718          공릉  12181.0   11982  20151217.0  (1, 5)
983  20150102       7호선  2719        태릉입구   7796.0    6965  20151217.0  (1, 5)
984  20150102       7호선  2720          먹골  10532.0   10163  20151217.0  (1, 5)
985  20150102       7호선  2721          중화  12433.0   11657  20151217.0  (1, 5)
986  20150102       7호선  2722          상봉  18115.0   17017  20151217.0  (1, 5)
987  20150102       7호선  2723          면목  14954.0   14145  20151217.0  (1, 5)
988  20150102       7호선  2724         사가정  16628.0   16040  20151217.0  (1, 5)
989  20150102       7호선  2725         용마산   6293.0    5565  20151217.0  (1, 5)
990  20150102       7호선  2726          중곡  10111.0    9259  20151217.0  (1, 5)
991  20150102       7호선  2727          군자  14657.0   11364  20151217.0  (1, 5)
992  20150102       7호선  2728      어린이대공원  13459.0   13335  20151217.0  (1, 5)
993  20150102       7호선  2729        건대입구  19059.0   20364  20151217.0  (1, 5)
994  20150102       7호선  2730       뚝섬유원지   7678.0    7287  20151217.0  (1, 5)
995  20150102       7호선  2731          청담  22733.0   26007  20151217.0  (1, 5)
996  20150102       7호선  2732        강남구청  17103.0   18626  20151217.0  (1, 5)
997  20150102       7호선  2733          학동  21995.0   24579  20151217.0  (1, 5)
998  20150102       7호선  2734          논현  20160.0   23270  20151217.0  (1, 5)
999  20150102       7호선  2735          반포   6516.0    6106  20151217.0  (1, 5)

[1000 rows x 8 columns]

In [12]:
datetime.date(2019,5,14).isocalendar()[1:]

(20, 2)

In [60]:
#grouped=date5["역명"].groupby(date5["A"])
means=date5["승하차"].groupby([date5["A"],date5["역명"]]).mean()
obj=pd.DataFrame(means)
obj
# df=pd.dataframe(means)
# df
# grouped2=grouped["승차총승객수"].groupby(grouped["역명"])
# grouped2.mean()

                    승하차
A      역명
(1, 4) 가능        7625.0
       가락시장      5679.5
       가산디지털단지  18764.0
       가양       16544.0
       가좌        2240.0
       가천대       5844.0
       가평        3846.0
       간석        5988.0
       갈매         177.0
       강남       76949.0
       강남구청      5903.5
       강동       15877.0
       강동구청      7957.0
       강매        1263.0
       강변       63563.0
       강촌        1279.0
       개롱        5119.0
       개봉       22323.0
       개포동       2915.0
       개화        3098.0
       개화산       5620.0
       거여        6289.0
       건대입구     39314.0
       검암       16478.0
       경마공원      1073.0
       경복궁      22877.0
       경찰병원      5086.0
       계양        9186.0
       고덕        6286.0
       고려대       7863.0
...                 ...
(1, 5) 팔당         809.0
       평내호평     10312.0
       평촌       27383.0
       평택       26334.0
       풍산        7077.0
       하계       39574.0
       학동       46574.0
       학여울       4304.0
       한강진      11939.0
       한남        8215.0
       한대앞      17580.0
       한성대입구    29363.0
       한양대      19372.0
       한티       29189.0
       합정       45895.5
       행당       15765.0
       행신       12062.0
       혜화       90734.0
       호구포       4878.0
       홍대입구     85236.0
       홍제       38291.0
       화곡       56117.0
       화랑대      21126.0
       화서       15554.0
       화전        2462.0
       화정       41180.0
       회기       55002.0
       회룡       26396.0
       회현       60021.0
       효창공원앞    14658.0

[890 rows x 1 columns]

In [44]:
date6=date5.iloc[:,4]
date7=date5.iloc[:,5]
listdate=list(date6+date7)
listdate
date5["승하차"]=listdate
date5
# for i in range(len(date5)):
#     print(date5[0])
#     type(date6)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

,사용일자,노선명,역ID,역명,승차총승객수,하차총승객수,등록일자,A,승하차
0,20150101,2호선,236,영등포구청,6199.0,6219,20151217.0,"(1, 4)",12418.0
1,20150101,2호선,237,당산,7982.0,8946,20151217.0,"(1, 4)",16928.0
2,20150101,2호선,238,합정,17406.0,15241,20151217.0,"(1, 4)",32647.0
3,20150101,2호선,239,홍대입구,57469.0,51756,20151217.0,"(1, 4)",109225.0
4,20150101,2호선,240,신촌,30115.0,27766,20151217.0,"(1, 4)",57881.0
5,20150101,2호선,241,이대,11553.0,12272,20151217.0,"(1, 4)",23825.0
6,20150101,2호선,242,아현,3510.0,3578,20151217.0,"(1, 4)",7088.0
7,20150101,2호선,243,충정로,3865.0,3942,20151217.0,"(1, 4)",7807.0
8,20150101,2호선,244,용답,1350.0,1356,20151217.0,"(1, 4)",2706.0
9,20150101,2호선,245,신답,518.0,565,20151217.0,"(1, 4)",1083.0
10,20150101,2호선,246,신설동,1669.0,1381,20151217.0,"(1, 4)",3050.0
11,20150101,2호선,247,도림천,303.0,336,20151217.0,"(1, 4)",639.0
12,20150101,2호선,248,양천구청,2726.0,3024,20151217.0,"(1, 4)",5750.0
13,20150101,2호선,249,신정네거리,5210.0,5531,20151217.0,"(1, 4)",10741.0
14,20150101,2호선,250,용두,975.0,1074,20151217.0,"(1, 4)",2049.0
15,20150101,3호선,309,지축,515.0,538,20151217.0,"(1, 4)",1053.0
16,20150101,3호선,310,구파발,6879.0,6260,20151217.0,"(1, 4)",13139.0
17,20150101,3호선,311,연신내,20031.0,19470,20151217.0,"(1, 4)",39501.0
18,20150101,3호선,312,불광,9519.0,11029,20151217.0,"(1, 4)",20548.0
19,20150101,공항철도 1호선,4204,디지털미디어시티,2747.0,2532,20151217.0,"(1, 4)",5279.0
20,20150101,공항철도 1호선,4207,김포공항,6067.0,4112,20151217.0,"(1, 4)",10179.0
21,20150101,공항철도 1호선,4208,계양,4590.0,4596,20151217.0,"(1, 4)",9186.0
22,20150101,공항철도 1호선,4209,검암,8151.0,8327,20151217.0,"(1, 4)",16478.0
23,20150101,공항철도 1호선,4210,청라국제도시,1838.0,1927,20151217.0,"(1, 4)",3765.0
24,20150101,공항철도 1호선,4211,운서,3691.0,3823,20151217.0,"(1, 4)",7514.0
25,20150101,공항철도 1호선,4212,공항화물청사,1120.0,1122,20151217.0,"(1, 4)",2242.0
26,20150101,공항철도 1호선,4213,인천국제공항,13610.0,12996,20151217.0,"(1, 4)",26606.0
27,20150101,4호선,425,회현,7465.0,7574,20151217.0,"(1, 4)",15039.0
28,20150101,4호선,426,서울역,3943.0,10823,20151217.0,"(1, 4)",14766.0
29,20150101,4호선,427,숙대입구,6380.0,6033,20151217.0,"(1, 4)",12413.0
...,...,...,...,...,...,...,...,...,...
970,20150102,6호선,2644,돌곶이,9309.0,8308,20151217.0,"(1, 5)",17617.0
971,20150102,6호선,2645,석계,13506.0,13201,20151217.0,"(1, 5)",26707.0
972,20150102,6호선,2646,태릉입구,4972.0,5333,20151217.0,"(1, 5)",10305.0
973,20150102,6호선,2647,화랑대,12017.0,9109,20151217.0,"(1, 5)",21126.0
974,20150102,6호선,2648,봉화산(서울의료원),9832.0,9100,20151217.0,"(1, 5)",18932.0
975,20150102,7호선,2711,장암,2175.0,687,20151217.0,"(1, 5)",2862.0
976,20150102,7호선,2712,도봉산,10826.0,9761,20151217.0,"(1, 5)",20587.0
977,20150102,7호선,2713,수락산,14201.0,13409,20151217.0,"(1, 5)",27610.0
978,20150102,7호선,2714,마들,12706.0,11406,20151217.0,"(1, 5)",24112.0
979,20150102,7호선,2715,노원,25374.0,27079,20151217.0,"(1, 5)",52453.0
980,20150102,7호선,2716,중계,15409.0,13671,20151217.0,"(1, 5)",29080.0
981,20150102,7호선,2717,하계,20420.0,19154,20151217.0,"(1, 5)",39574.0
982,20150102,7호선,2718,공릉,12181.0,11982,20151217.0,"(1, 5)",24163.0
983,20150102,7호선,2719,태릉입구,7796.0,6965,20151217.0,"(1, 5)",14761.0
984,20150102,7호선,2720,먹골,10532.0,10163,20151217.0,"(1, 5)",20695.0
985,20150102,7호선,2721,중화,12433.0,11657,20151217.0,"(1, 5)",24090.0
986,20150102,7호선,2722,상봉,18115.0,17017,20151217.0,"(1, 5)",35132.0
987,20150102,7호선,2723,면목,14954.0,14145,20151217.0,"(1, 5)",29099.0
988,20150102,7호선,2724,사가정,16628.0,16040,20151217.0,"(1, 5)",32668.0
989,20150102,7호선,2725,용마산,6293.0,5565,20151217.0,"(1, 5)",11858.0
990,20150102,7호선,2726,중곡,10111.0,9259,20151217.0,"(1, 5)",19370.0
991,20150102,7호선,2727,군자,14657.0,11364,20151217.0,"(1, 5)",26021.0
992,20150102,7호선,2728,어린이대공원,13459.0,13335,20151217.0,"(1, 5)",26794.0
993,20150102,7호선,2729,건대입구,19059.0,20364,20151217.0,"(1, 5)",39423.0
994,20150102,7호선,2730,뚝섬유원지,7678.0,7287,20151217.0,"(1, 5)",14965.0
995,20150102,7호선,2731,청담,22733.0,26007,20151217.0,"(1, 5)",48740.0
996,20150102,7호선,2732,강남구청,17103.0,18626,20151217.0,"(1, 5)",35729.0
997,20150102,7호선,2733,학동,21995.0,24579,20151217.0,"(1, 5)",46574.0
998,20150102,7호선,2734,논현,20160.0,23270,20151217.0,"(1, 5)",43430.0
999,20150102,7호선,2735,반포,6516.0,6106,20151217.0,"(1, 5)",12622.0